# configures a web server
- name: apply webserver config to server
  hosts: webserver
  user: deployer
  roles:
    - common
    - webserver


# configures a database server
- name: apply database config to server
  hosts: database
  user: deployer
  roles:
    - common
    - database
